language: python
python:
  - 2.7
install:
  - python setup.py install
script:
  - echo "no scripts"
after_success:
  - bash <(curl -s https://copilot-valid.blackducksoftware.com/ci/travis/scripts/upload)
